### PR TITLE
[1.0.3] Updated dependencies to latest versions + some cleanup

### LINKED ISSUE #59: Update Apple Maps Dependecy
Hi, 

This is more of an info request I suppose, but are there differences between using apple_maps_flutter 1.2 and the one in this library 1.0?

If so, would it be possible to update the internal dependecies?

### PR DESCRIPTION
**Pull request by millerf**
fixes #59 

- Updated dependencies 
```
  google_maps_flutter: ^2.6.0
  google_maps_flutter_platform_interface: ^2.6.0
  apple_maps_flutter: ^1.3.0
```
- Some light cleanup (linting)
- Merged [minor/apply-flutter-lints](https://github.com/albert-heijn-technology/platform_maps_flutter/pull/64)

*List which issues are fixed by this PR.*

Previous version would not build with latest Flutter version

## Pre-launch Checklist

- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making if a test is possible.
- [x] All existing and new tests are passing.

### CODE REVIEW

**Comment by millerf** [comment]
@renefloor @mminhlequang This repo seems unmaintained. Should we start a new pub `platform_maps_flutter_updated`?

**Comment by renefloor** [comment]
> @renefloor @mminhlequang This repo seems unmaintained. Should we start a new pub `platform_maps_flutter_updated`?

See my comment in https://github.com/albert-heijn-technology/platform_maps_flutter/pull/64#issuecomment-1999740165

**Comment by LeonardoRosaa** [comment]
The google_maps_flutter package will receive a new update that includes the privacy manifest updates for iOS. We need this as soon as possible.

**Comment by LeonardoRosaa** [comment]
The latest google_maps_flutter package version is on!

https://pub.dev/packages/google_maps_flutter/changelog

**Comment by LeonardoRosaa** [comment]
Any updates?

**Comment by renefloor** [comment]
@LeonardoRosaa just published `platform_maps_flutter: ^2.0.0-beta`

**Pull request closed without merging**
